CREATE TABLE Team(
	TeamID INTEGER AUTOINCREMENT;

CREATE TABLE LocationSlot(
	SlotID INTEGER AUTOINCREMENT;

CREATE TABLE Person(
	PersonID INTEGER AUTOINCREMENT;

CREATE TABLE Assignment(
	AssignID INTEGER AUTOINCREMENT;

CREATE TABLE Floorplan(
	Image varbinary(max);

CREATE TABLE Location(
	LocID INTEGER AUTOINCREMENT;

CREATE TABLE PersonSlot(
	PersonID INTEGER NOT NULL,
	SlotTypeID INTEGER NOT NULL,
 PRIMARY KEY 
(
	PersonID ASC,
	SlotTypeID ASC
);

CREATE TABLE SlotType(
	SlotTypeID INTEGER AUTOINCREMENT;

CREATE TABLE Unavailability(
	PersonID INTEGER NOT NULL,
	StartDate datetime2(7);